# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: bytecharts/byte-charts.dev
  branch: main

media_folder: static/uploads
public_folder: /uploads

collections: []
