<script>
	import { onMount, tick } from 'svelte';
	import { resolve } from '$app/paths';
	import 'photoswipe/style.css';

	const basePath = '/images/charts/gallery/static';
	const thumbPath = '/images/charts/gallery/thumbs';

	const toTitle = (file) => {
		const stem = file.replace(/\.(png|jpe?g|webp)$/i, '');
		const number = stem.match(/(\d+)\s*$/)?.[1];
		if (number) return `Chart ${number}`;
		return stem.replace(/[_-]+/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());
	};

	const files = [
		'static__5.png',
		'static__2.png',
		'static__19.png',
		'static__3.png',
		'static__31.png',
		'static__8.png',
		'static__6.webp',
		'static__4.png',
		'static__0.png',
		'static__10.png',
		'static__32.png',
		'static__11.png',
		'static__12.png',
		'static__13.png',
		'static__14.png',
		'static__15.png',
		'static__18.png',
		'static__26.webp',
		'static__28.png',
		'static__1.png',
		'static__21.webp',
		'static__22.webp',
		'static__23.png',
		'static__24.webp',
		'static__7.png'
	];

	/*
	 * gallery.json is generated by Sharp (scripts/generate-thumbnails.js):
	 *
	 * [
	 *   {
	 *     "file": "static__5.png",
	 *     "width": 2400,
	 *     "height": 1600,
	 *     "thumbWidth": 600,
	 *     "thumbHeight": 400,
	 *     // hand-edited, preserved across regens:
	 *     "title": "…",
	 *     "subtitle": "…",
	 *     "year": "2026",
	 *     "tags": ["dataviz"],
	 *     // marks the item as Interactive (opens in new tab):
	 *     "interactive": "True", "url": "https://…"
	 *   }
	 * ]
	 */
	let items = $state([]);
	let videoItems = $state([]);

	/*
	 * static/videos/videos.json is hand-edited (titles, subtitles, years, tags):
	 *
	 * [
	 *   {
	 *     "src": "/videos/Chasing_Love.mp4",
	 *     "poster": "/videos/Chasing_Love.jpg",
	 *     "title": "…",
	 *     "subtitle": "…",
	 *     "year": "2026",
	 *     "tags": ["dataviz"],
	 *     "width": 1080,
	 *     "height": 1920
	 *   }
	 * ]
	 */
	const normalizeVideoTags = (tags) => {
		if (!tags) return [];
		const rawList = Array.isArray(tags) ? tags : [tags];
		return rawList
			.flatMap((tag) => String(tag).split(','))
			.map((tag) => tag.trim())
			.filter(Boolean);
	};

	const normalizeVideo = (entry) => ({
		src: entry?.src ?? '',
		poster: entry?.poster ?? entry?.src ?? '',
		title:
			entry?.title ??
			String(entry?.src ?? 'Video')
				.split('/')
				.pop(),
		subtitle: entry?.subtitle ?? '',
		year: entry?.year ?? '',
		tags: normalizeVideoTags(entry?.tags),
		width: entry?.width ?? 1280,
		height: entry?.height ?? 720,
		isVideo: true,
		kind: 'video'
	});

	let galleryItems = $state([]);
	let galleryStatus = $state('loading');

	let activeFilter = $state('charts');

	const filters = [
		{ id: 'charts', label: 'Static' },
		{ id: 'video', label: 'Motion' },
		{ id: 'interactive', label: 'Interactive' }
	];

	let filteredItems = $derived(galleryItems.filter((item) => item.kind === activeFilter));

	let lightbox;
	let mounted = false;
	let lastLightboxKey = '';

	// Floating filter bar: appears fixed at the bottom once the inline
	// filter menu scrolls out of view, rides above the footer near the
	// page bottom, and hides again when the inline menu is visible.
	let filterEl;
	let footerEl;
	let pastFilters = $state(false);
	let filtersVisible = $state(true);
	let barOffset = $state(0);
	let showFloating = $derived(pastFilters && !filtersVisible);

	async function setupLightbox() {
		lightbox?.destroy();
		lightbox = undefined;
		await tick();
		if (!mounted || galleryItems.length === 0) return;

		const { default: PhotoSwipeLightbox } = await import('photoswipe/lightbox');
		const { default: PhotoSwipeVideoPlugin } = await import('photoswipe-video-plugin');
		lightbox = new PhotoSwipeLightbox({
			gallery: '#gallery',
			// External interactive-site links must not open the lightbox.
			children: 'a[data-lightbox]',
			pswpModule: () => import('photoswipe')
		});
		new PhotoSwipeVideoPlugin(lightbox, {});
		lightbox.init();
	}

	// Re-init the lightbox whenever the visible set changes: filtering
	// adds/removes <a> children, which PhotoSwipe would otherwise not pick up.
	$effect(() => {
		const key = `${galleryStatus}:${activeFilter}`;
		if (galleryStatus !== 'ready' || key === lastLightboxKey) return;
		lastLightboxKey = key;
		setupLightbox();
	});

	onMount(() => {
		mounted = true;
		let cancelled = false;
		footerEl = document.querySelector('footer');

		// Track scroll position: mark filters as passed, and lift the
		// floating bar above the footer when it comes into view.
		const onScroll = () => {
			if (filterEl && filterEl.getBoundingClientRect().top < 0) pastFilters = true;
			if (footerEl) {
				const overlap = window.innerHeight - footerEl.getBoundingClientRect().top;
				barOffset = overlap > 0 ? overlap + 12 : 0;
			}
		};
		window.addEventListener('scroll', onScroll, { passive: true });
		const filterObserver = new IntersectionObserver(
			(entries) => {
				filtersVisible = entries[0]?.isIntersecting ?? true;
			},
			{ threshold: 0 }
		);
		if (filterEl) filterObserver.observe(filterEl);
		onScroll();

		(async () => {
			try {
				// Videos are hand-edited metadata; a missing file just means no videos.
				try {
					const videosResponse = await fetch(resolve('/videos/videos.json'));
					if (videosResponse.ok) {
						const videos = await videosResponse.json();
						if (cancelled) return;
						videoItems = (Array.isArray(videos) ? videos : []).map(normalizeVideo);
					}
				} catch {
					// Keep the gallery working without videos.
				}
				if (cancelled) return;

				const response = await fetch(resolve('/images/charts/gallery/gallery.json'));
				if (!response.ok) throw new Error(`HTTP ${response.status}`);
				const metadata = await response.json();
				if (cancelled) return;
				items = files.map((file) => {
					const info = metadata.find((item) => item.file === file);
					const width = info?.width ?? 1200;
					const height = info?.height ?? 800;
					const thumbWidth = info?.thumbWidth ?? 600;
					const thumbHeight = info?.thumbHeight ?? Math.round((thumbWidth * height) / width);
					// Entries with a `url`/`link` (edited manually in gallery.json)
					// belong to the Interactive category and open the URL in a new
					// tab instead of the lightbox. `interactive: "True"` marks them
					// explicitly; the URL is what activates the behavior.
					const link =
						typeof info?.link === 'string'
							? info.link
							: typeof info?.url === 'string'
								? info.url
								: undefined;
					const isInteractive = Boolean(link);

					return {
						src: `${basePath}/${file}`,
						thumb: `${thumbPath}/${file.replace(/\.(png|jpe?g|webp)$/i, '.webp')}`,
						thumbAvif: `${thumbPath}/${file.replace(/\.(png|jpe?g|webp)$/i, '.avif')}`,
						// Real thumb dimensions from gallery.json reserve the layout
						// box and prevent CLS.
						thumbWidth,
						thumbHeight,
						title: info?.title ?? toTitle(file),
						subtitle: info?.subtitle,
						year: info?.year,
						tags: Array.isArray(info?.tags) ? info.tags : [],
						link,
						width,
						height,
						kind: isInteractive ? 'interactive' : 'charts'
					};
				});

				galleryItems = [...videoItems, ...items];
				galleryStatus = 'ready';
			} catch {
				// Fall back to the video-only gallery so the page still works.
				if (!cancelled) {
					galleryItems = [...videoItems];
					galleryStatus = 'error';
				}
			}
		})();

		return () => {
			mounted = false;
			cancelled = true;
			window.removeEventListener('scroll', onScroll);
			filterObserver.disconnect();
			lightbox?.destroy();
			lightbox = undefined;
		};
	});
</script>

{#snippet caption(item)}
	<div class="pt-3">
		<h3 class="text-lg font-bold">{item.title}</h3>
		{#if item.subtitle || item.year}
			<p class="mt-1 text-xs tracking-[0.2em] text-base-content/50 uppercase">
				{[item.subtitle, item.year].filter(Boolean).join(' · ')}
			</p>
		{/if}
		{#if (item.tags ?? []).length > 0}
			<div class="mt-2 flex flex-wrap gap-2">
				{#each item.tags as tag (tag)}
					<span class="badge-static badge badge-outline badge-sm">{tag}</span>
				{/each}
			</div>
		{/if}
	</div>
{/snippet}

{#snippet filterButtons()}
	{#each filters as filter (filter.id)}
		<button
			type="button"
			onclick={() => (activeFilter = filter.id)}
			aria-pressed={activeFilter === filter.id}
			class={`pressable cursor-pointer px-2 py-1 text-base text-base-content sm:text-lg `}
		>
			<span class="hvr-lines-square" class:current-tab={activeFilter === filter.id}>
				{filter.label}
			</span>
		</button>
	{/each}
{/snippet}

<section class="px-6 py-16">
	<div class="mx-auto max-w-6xl">
		<div
			class="card-custom relative mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"
		>
			<div>
				<h1 class="text-4xl font-black tracking-wide sm:text-5xl">Visual Stories</h1>

				<p class="mt-3 max-w-2xl text-base-content/70">
					A curated collection of work from public challenges like #30DayChartChallenge and
					#TidyTuesday, exploring patterns and stories that emerge from the data.
				</p>
			</div>
		</div>

		<div
			bind:this={filterEl}
			class="about-page-hack mb-10 flex flex-wrap gap-2 bg-base-100 p-4"
			role="group"
			aria-label="Filter gallery"
		>
			{@render filterButtons()}
		</div>

		<div class="about-page-hack grid min-h-[50vh] items-center bg-base-100 p-4">
			{#if galleryStatus === 'loading'}
				<p class="text-center text-base-content/60" role="status">Loading gallery…</p>
			{:else}
				{#if galleryStatus === 'error'}
					<p class="mb-4 text-center text-base-content/60" role="alert">
						Couldn’t load the chart images — showing videos only.
					</p>
				{/if}
				{#if filteredItems.length === 0}
					<p class="text-center text-base-content/60">No items in this category yet.</p>
				{:else}
					<div id="gallery" class="columns-1 gap-6 sm:columns-2 lg:columns-3">
						{#each filteredItems as item (item.src)}
							{#if item.isVideo}
								<!-- Videos handled by PhotoSwipe via photoswipe-video-plugin -->
								<div
									class="gallery-card group relative mb-6 block w-full break-inside-avoid overflow-hidden border border-base-300 bg-base-100/80"
								>
									<a
										href={resolve(item.src)}
										data-lightbox
										data-pswp-type="video"
										data-pswp-video-src={item.src}
										data-pswp-width={item.width}
										data-pswp-height={item.height}
										aria-label={`Open ${item.title}`}
										class="relative block"
									>
										<img
											src={item.poster}
											alt=""
											width={item.width}
											height={item.height}
											loading="lazy"
											decoding="async"
											class="gallery-image block w-full"
										/>

										<div class="gallery-video-overlay">
											<svg viewBox="0 0 24 24" aria-hidden="true" class="gallery-video-icon">
												<path
													fill="currentColor"
													d="M8 5.14v13.72a1 1 0 0 0 1.52.86l10.29-6.86a1 1 0 0 0 0-1.72L9.52 4.28A1 1 0 0 0 8 5.14z"
												/>
											</svg>

											<span class="gallery-video-label">Video</span>
										</div>
									</a>
									{@render caption(item)}
								</div>
							{:else if item.link}
								<!-- Interactive sites open the webpage in a new tab -->
								<div
									class="gallery-card group relative mb-6 block w-full break-inside-avoid overflow-hidden border border-base-300 bg-base-100/80"
								>
									<!-- eslint-disable svelte/no-navigation-without-resolve -- external interactive-site URL; must not be base-resolved -->
									<a
										href={item.link}
										target="_blank"
										rel="noopener noreferrer"
										aria-label={`${item.title} (opens external site)`}
										class="relative block"
									>
										<picture class="block">
											<source srcset={item.thumbAvif} type="image/avif" />
											<img
												src={item.thumb}
												alt={item.title}
												width={item.thumbWidth}
												height={item.thumbHeight}
												loading="lazy"
												decoding="async"
												class="gallery-image block w-full"
											/>
										</picture>
										<span class="absolute top-2 right-2 badge badge-neutral" aria-hidden="true">
											↗ Site
										</span>
									</a>
									<!-- eslint-enable svelte/no-navigation-without-resolve -->
									{@render caption(item)}
								</div>
							{:else}
								<!-- Images handled by PhotoSwipe -->
								<div
									class="gallery-card group relative mb-6 block w-full break-inside-avoid overflow-hidden border border-base-300 bg-base-100/80"
								>
									<a
										href={resolve(item.src)}
										data-lightbox
										data-pswp-width={item.width}
										data-pswp-height={item.height}
										aria-label={`Open ${item.title}`}
										class="block"
									>
										<picture class="block">
											<source srcset={item.thumbAvif} type="image/avif" />
											<img
												src={item.thumb}
												alt={item.title}
												width={item.thumbWidth}
												height={item.thumbHeight}
												loading="lazy"
												decoding="async"
												class="gallery-image block w-full"
											/>
										</picture>
									</a>
									{@render caption(item)}
								</div>
							{/if}
						{/each}
					</div>
				{/if}
			{/if}
		</div>
	</div>

	<!-- Floating filter bar: fixed to the bottom once the inline menu
		scrolls out of view; rides above the footer near the page bottom;
		hides when the inline menu is visible again. -->
	<div
		class={`fixed inset-x-0 z-50 px-6 transition-all duration-300 ${showFloating ? 'translate-y-0 opacity-100' : 'pointer-events-none translate-y-24 opacity-0'}`}
		style={`bottom: calc(0.75rem + env(safe-area-inset-bottom, 0px) + ${barOffset}px)`}
		role="group"
		aria-label="Filter gallery"
	>
		<div
			class="mx-auto flex w-full max-w-6xl flex-wrap justify-center gap-2 rounded-lg border border-base-300 bg-base-100/95 px-4 py-3 shadow-xl backdrop-blur"
		>
			{@render filterButtons()}
		</div>
	</div>
</section>

<style>
	.gallery-card {
		padding: 1em;
		transition:
			transform 0.3s ease,
			box-shadow 0.3s ease;
	}

	.gallery-card:hover {
		transform: translateY(-4px);
		box-shadow: 0 20px 40px -30px rgba(0, 0, 0, 0.35);
	}

	.gallery-image {
		height: auto;
		transition: transform 0.3s ease;
	}

	.gallery-card:hover .gallery-image {
		transform: scale(1.05);
	}

	.gallery-video-overlay {
		position: absolute;
		inset: 0;
		display: grid;
		place-items: center;
		gap: 8px;
		background: linear-gradient(180deg, rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.55));
		text-transform: uppercase;
		letter-spacing: 0.2em;
		font-size: 0.7rem;
	}

	.gallery-video-icon {
		width: 3rem;
		height: 3rem;
	}

	.gallery-video-label {
		font-weight: 700;
	}

	/* Tailwind preflight clamps replaced elements to max-width: 100%.
	 * The slide holder (.pswp__zoom-wrap) is 0px wide (sized by transform),
	 * which collapses PhotoSwipe videos to 0px wide. Opt out like images do. */
	:global(.pswp__item video) {
		max-width: none;
	}
</style>
