<script>
	import { onMount, tick } from 'svelte';
	import { resolve } from '$app/paths';
	import 'photoswipe/style.css';

	const basePath = '/images/charts/gallery/static';
	const thumbPath = '/images/charts/gallery/thumbs';

	const toTitle = (file) =>
		file
			.replace(/\.(png|webp)$/i, '')
			.replace(/[_-]+/g, ' ')
			.replace(/\b\w/g, (char) => char.toUpperCase());

	const files = [
		'static__5.png',
		'static__2.png',
		'static__19.png',
		'static__3.png',
		'static__8.png',
		'static__6.webp',
		'static__4.png',
		'static__0.png',
		'static__10.png',
		'static__11.png',
		'static__12.png',
		'static__13.png',
		'static__14.png',
		'static__15.png',
		'static__18.png',
		'static__1.png',
		'static__21.webp',
		'static__22.webp',
		'static__23.png',
		'static__24.webp',
		'static__7.png'
	];

	/*
	 * gallery.json is generated by Sharp:
	 *
	 * [
	 *   {
	 *     "file": "static__5.png",
	 *     "width": 2400,
	 *     "height": 1600
	 *   }
	 * ]
	 */
	let items = $state([]);

	const videoItems = [
		{
			src: '/videos/Chasing_Love.mp4',
			poster: '/videos/Chasing_Love.jpg',
			title: 'Chasing Love in Hollywood Rom-coms',
			width: 1080,
			height: 1920,
			isVideo: true
		},
		{
			src: '/videos/OBEs.mp4',
			poster: '/videos/OBEs.jpg',
			title: 'Out of Body Experiences and their stories',
			width: 1080,
			height: 1920,
			isVideo: true
		},
		{
			src: '/videos/Manta_Rays_H.mp4',
			poster: '/videos/Manta_Rays.jpg',
			title: 'Manta Rays Observations off the coast of Australia',
			width: 1440,
			height: 2560,
			isVideo: true
		},
		{
			src: '/videos/IPL_Team_Valuations.mp4',
			poster: '/videos/IPL_Team_Valuations.jpg',
			title: 'IPL Team Valuations',
			width: 1280,
			height: 720,
			isVideo: true
		}
	];

	let galleryItems = $state(videoItems);

	let lightbox;

	onMount(() => {
		let cancelled = false;

		(async () => {
			try {
				const response = await fetch('/images/charts/gallery/gallery.json');
				if (!response.ok) return;
				const metadata = await response.json();
				if (cancelled) return;

				items = files.map((file) => {
					const info = metadata.find((item) => item.file === file);
					const width = info?.width ?? 1200;
					const height = info?.height ?? 800;

					return {
						src: `${basePath}/${file}`,
						thumb: `${thumbPath}/${file.replace(/\.(png|webp)$/i, '.webp')}`,
						thumbAvif: `${thumbPath}/${file.replace(/\.(png|webp)$/i, '.avif')}`,
						// Thumbs are 600px wide, aspect preserved — reserves layout box, prevents CLS.
						thumbWidth: 600,
						thumbHeight: Math.round((600 * height) / width),
						title: '#' + toTitle(file),
						width,
						height
					};
				});

				galleryItems = [...videoItems, ...items];

				await tick();
				if (cancelled) return;

				const { default: PhotoSwipeLightbox } = await import('photoswipe/lightbox');
				const { default: PhotoSwipeVideoPlugin } = await import('photoswipe-video-plugin');
				lightbox = new PhotoSwipeLightbox({
					gallery: '#gallery',
					children: 'a',
					pswpModule: () => import('photoswipe')
				});
				new PhotoSwipeVideoPlugin(lightbox, {});
				lightbox.init();
			} catch {
				// Keep video-only gallery if metadata can't load.
			}
		})();

		return () => {
			cancelled = true;
			lightbox?.destroy();
			lightbox = undefined;
		};
	});
</script>

<section class="px-6 py-16">
	<div class="mx-auto max-w-6xl">
		<div
			class="card-custom relative mb-10 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"
		>
			<div>
				<h1 class="text-4xl font-black tracking-wide sm:text-5xl">Visual Stories</h1>

				<p class="mt-3 max-w-2xl text-base-content/70">
					A curated collection of work from public challenges like #30DayChartChallenge and
					#TidyTuesday, exploring patterns and stories that emerge from the data.
				</p>
			</div>
		</div>

		<div id="gallery" class="columns-1 gap-6 sm:columns-2 lg:columns-3">
			{#each galleryItems as item (item.src)}
				{#if item.isVideo}
					<!-- Videos handled by PhotoSwipe via photoswipe-video-plugin -->
					<a
						href={resolve(item.src)}
						data-pswp-type="video"
						data-pswp-video-src={item.src}
						data-pswp-width={item.width}
						data-pswp-height={item.height}
						aria-label={item.title}
						class="gallery-card group relative mb-6 block w-full break-inside-avoid overflow-hidden border border-base-300 bg-base-100/80"
					>
						<img
							src={item.poster}
							alt={item.title}
							width={item.width}
							height={item.height}
							loading="lazy"
							decoding="async"
							class="gallery-image block w-full"
						/>

						<div class="gallery-video-overlay">
							<svg viewBox="0 0 24 24" aria-hidden="true" class="gallery-video-icon">
								<path
									fill="currentColor"
									d="M8 5.14v13.72a1 1 0 0 0 1.52.86l10.29-6.86a1 1 0 0 0 0-1.72L9.52 4.28A1 1 0 0 0 8 5.14z"
								/>
							</svg>

							<span class="gallery-video-label">Video</span>
						</div>
					</a>
				{:else}
					<!-- Images handled by PhotoSwipe -->
					<a
						href={resolve(item.src)}
						data-pswp-width={item.width}
						data-pswp-height={item.height}
						class="gallery-card group relative mb-6 block w-full break-inside-avoid overflow-hidden border border-base-300 bg-base-100/80"
					>
						<picture class="block">
							<source srcset={item.thumbAvif} type="image/avif" />
							<img
								src={item.thumb}
								alt={item.title}
								width={item.thumbWidth}
								height={item.thumbHeight}
								loading="lazy"
								decoding="async"
								class="gallery-image block w-full"
							/>
						</picture>
					</a>
				{/if}
			{/each}
		</div>
	</div>
</section>

<style>
	.gallery-card {
		padding: 1em;
		transition:
			transform 0.3s ease,
			box-shadow 0.3s ease;
	}

	.gallery-card:hover {
		transform: translateY(-4px);
		box-shadow: 0 20px 40px -30px rgba(0, 0, 0, 0.35);
	}

	.gallery-image {
		height: auto;
		transition: transform 0.3s ease;
	}

	.gallery-card:hover .gallery-image {
		transform: scale(1.05);
	}

	.gallery-video-overlay {
		position: absolute;
		inset: 0;
		display: grid;
		place-items: center;
		gap: 8px;
		background: linear-gradient(180deg, rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.55));
		text-transform: uppercase;
		letter-spacing: 0.2em;
		font-size: 0.7rem;
	}

	.gallery-video-icon {
		width: 3rem;
		height: 3rem;
	}

	.gallery-video-label {
		font-weight: 700;
	}

	/* Tailwind preflight clamps replaced elements to max-width: 100%.
	 * The slide holder (.pswp__zoom-wrap) is 0px wide (sized by transform),
	 * which collapses PhotoSwipe videos to 0px wide. Opt out like images do. */
	:global(.pswp__item video) {
		max-width: none;
	}
</style>
